#19 Configure Entity Framework
Jherrera31/MovieStore pull request #21
Opened 2017-10-22 22:47 UTC by JeffersonBenzan

2017-10-22 22:52 UTC, Willjobs94 requested changes
Agrega tambien un Migration que se llame `InitialMigration` que cree las tablas, en la base de datos.

2017-10-22 22:52 UTC, Willjobs94 commented on MovieStore/MovieStore/web.config
> +<connectionStrings><add name="MovieStoreDbContext" connectionString="data source=JEFFERBT\JEFFERSON;initial catalog=MovieStore.Models.MovieStoreDbContext;integrated security=True;MultipleActiveResult
Cambia el nombre de la base de dato a MoviesStoreDb

2017-10-22 22:52 UTC, Willjobs94 commented on MovieStore/MovieStore/Models/MovieStoreDbContext.cs
> +            : base("name=MovieStoreDbContext")
pon que el conection string se llame MoviesStoreDb

2017-10-23 00:27 UTC, Willjobs94 requested changes

2017-10-23 00:27 UTC, Willjobs94 commented on MovieStore/MovieStore/web.config
> +<connectionStrings><add name="MoviesStoreDb" connectionString="data source=JEFFERBT\JEFFERSON;initial catalog=MovieStore.Models.MovieStoreDbContext;integrated security=True;MultipleActiveResultSets=T
Cambia el nombre de la base de datos tambien en el connection string.
Es decir que diga `Initial Catalog=MovieStoreDb`

2017-10-23 00:27 UTC, Willjobs94 commented on MovieStore/MovieStore/Migrations/Configuration.cs
> +        protected override void Seed(MovieStore.Models.MovieStoreDbContext context)
simplifical el nombre, osea agrega using.

2017-10-23 00:27 UTC, Willjobs94 commented on MovieStore/MovieStore/Models/MovieStoreDbContext.cs
> +            Database.SetInitializer(new MigrateDatabaseToLatestVersion<MovieStoreDbContext, MovieStore.Migrations.Configuration>("MoviesStoreDb"));
simplica el nombre

2017-10-23 00:30 UTC, JeffersonBenzan commented on MovieStore/MovieStore/web.config
> +<connectionStrings><add name="MoviesStoreDb" connectionString="data source=JEFFERBT\JEFFERSON;initial catalog=MovieStore.Models.MovieStoreDbContext;integrated security=True;MultipleActiveResultSets=T
Ok, ese es el nombre que se crea en SQL Server entonces ?

2017-10-23 00:31 UTC, JeffersonBenzan commented on MovieStore/MovieStore/web.config
> +<connectionStrings><add name="MoviesStoreDb" connectionString="data source=JEFFERBT\JEFFERSON;initial catalog=MovieStore.Models.MovieStoreDbContext;integrated security=True;MultipleActiveResultSets=T
Deberia nuevamente borrar todo y generar ?

2017-10-23 00:35 UTC, Willjobs94 commented on MovieStore/MovieStore/web.config
> +<connectionStrings><add name="MoviesStoreDb" connectionString="data source=JEFFERBT\JEFFERSON;initial catalog=MovieStore.Models.MovieStoreDbContext;integrated security=True;MultipleActiveResultSets=T
Si

2017-10-23 00:52 UTC, Willjobs94 approved these changes

2017-10-23 00:52 UTC, merged